project:
  type: website
  output-dir: docs

website:
  title: "Matthew DeHaven"
  favicon: static-content/logo/logo-32x32.png
  navbar:
    logo: static-content/logo/logo.svg
    left:
      - href: about.qmd
        text: About
      - href: research/index.qmd
        text: Research
      - href: teaching/index.qmd
        text: Teaching
      - href: CV/cv.qmd
        text: CV
    toggle-position: "right"
  page-footer:
    left: "[Source code](https://github.com/matdehaven/matdehaven.github.io)."
    center: Â© 2024  &middot; Created with [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/) .
    right:
      - href: https://github.com/matdehaven
        icon: github
format:
  html:
    theme: 
      - simplex
      - custom-theme.scss
    toc: true

editor:
  render-on-save: true
